const graphlProducts = [

  // ─── HOODIES ───────────────────────────────────────────
  {
    id: 1,
    slug: "graphl-hoodie-v1",
    title: "Graphl Hoodie V1",
    brand: "GRAPHL",
    price: 1999,
    comparePrice: 2499,
    description: "Crafted from premium heavyweight cotton with an oversized fit for everyday comfort and timeless streetwear style.",
    images: ["/products/hoodies/hoodie1.jpg"],
    colors: [{ name: "Black", hex: "#111111" }, { name: "White", hex: "#F5F5F5" }],
    sizes: ["S", "M", "L", "XL"],
    category: "hoodies",
    stock: 50,
    featured: true,
    rating: 4.9,
    reviews: 324,
  },
  {
    id: 2,
    slug: "graphl-hoodie-v2",
    title: "Graphl Hoodie V2",
    brand: "GRAPHL",
    price: 1999,
    comparePrice: 2499,
    description: "Same premium heavyweight build in a rich new colourway for a bolder streetwear look.",
    images: ["/products/hoodies/hoodie2.jpg"],
    colors: [{ name: "Brown", hex: "#5C3A1E" }, { name: "Beige", hex: "#C9B99A" }],
    sizes: ["S", "M", "L", "XL"],
    category: "hoodies",
    stock: 45,
    featured: true,
    rating: 4.8,
    reviews: 210,
  },
  {
    id: 3,
    slug: "graphl-hoodie-v3",
    title: "Graphl Hoodie V3",
    brand: "GRAPHL",
    price: 1999,
    comparePrice: 2499,
    description: "Oversized and relaxed — built for those who wear comfort like a statement.",
    images: ["/products/hoodies/hoodie3.jpg"],
    colors: [{ name: "Olive", hex: "#556B2F" }, { name: "Black", hex: "#111111" }],
    sizes: ["S", "M", "L", "XL"],
    category: "hoodies",
    stock: 40,
    featured: false,
    rating: 4.7,
    reviews: 178,
  },
  {
    id: 4,
    slug: "graphl-hoodie-v4",
    title: "Graphl Hoodie V4",
    brand: "GRAPHL",
    price: 1999,
    comparePrice: 2499,
    description: "Street-ready heavyweight hoodie with a clean minimal finish.",
    images: ["/products/hoodies/hoodie4.jpg"],
    colors: [{ name: "Grey", hex: "#888888" }, { name: "Charcoal", hex: "#333333" }],
    sizes: ["S", "M", "L", "XL"],
    category: "hoodies",
    stock: 35,
    featured: false,
    rating: 4.6,
    reviews: 143,
  },
  {
    id: 5,
    slug: "graphl-hoodie-v5",
    title: "Graphl Hoodie V5",
    brand: "GRAPHL",
    price: 1999,
    comparePrice: 2499,
    description: "The boldest Graphl hoodie yet — limited stock, unlimited attitude.",
    images: ["/products/hoodies/hoodie5.jpg"],
    colors: [{ name: "White", hex: "#F5F5F5" }, { name: "Olive", hex: "#556B2F" }],
    sizes: ["S", "M", "L", "XL"],
    category: "hoodies",
    stock: 30,
    featured: true,
    rating: 4.9,
    reviews: 96,
  },

  // ─── TSHIRTS ───────────────────────────────────────────
  {
    id: 6,
    slug: "graphl-oversized-tshirt-v1",
    title: "Graphl Oversized T-Shirt V1",
    brand: "GRAPHL",
    badge: "BESTSELLER", 
    price: 999,
    comparePrice: 1499,
    description: "Premium oversized tee crafted from heavyweight cotton for everyday comfort and effortless streetwear style.",
    images: ["/products/tshirts/tshirt1.jpg", "/products/tshirts/tshirt2.jpg"],
    colors: [{ name: "Black", hex: "#111111" }, { name: "White", hex: "#F5F5F5" }],
    sizes: ["S", "M", "L", "XL"],
    category: "tshirts",
    stock: 100,
    featured: true,
    rating: 4.8,
    reviews: 185,
  },
  {
    id: 7,
    slug: "graphl-oversized-tshirt-v2",
    title: "Graphl Oversized T-Shirt V2",
    brand: "GRAPHL",
    price: 999,
    comparePrice: 1499,
    description: "A clean minimal oversized tee that pairs with everything in your wardrobe.",
    images: ["/products/tshirts/tshirt3.jpg", "/products/tshirts/tshirt5.jpg"],
    colors: [{ name: "Grey", hex: "#888888" }, { name: "Charcoal", hex: "#333333" }],
    sizes: ["S", "M", "L", "XL"],
    category: "tshirts",
    stock: 80,
    featured: false,
    rating: 4.6,
    reviews: 142,
  },
  {
    id: 8,
    slug: "graphl-oversized-tshirt-v3",
    title: "Graphl Oversized T-Shirt V3",
    brand: "GRAPHL",
    price: 999,
    comparePrice: 1499,
    description: "Premium oversized tee for everyday streetwear comfort.",
    images: ["/products/tshirts/tshirt6.jpg", "/products/tshirts/tshirt7.jpg"],
    colors: [{ name: "Black", hex: "#111111" }, { name: "White", hex: "#F5F5F5" }],
    sizes: ["S", "M", "L", "XL"],
    category: "tshirts",
    stock: 80,
    featured: false,
    rating: 4.6,
    reviews: 110,
  },
  {
    id: 9,
    slug: "graphl-oversized-tshirt-v4",
    title: "Graphl Oversized T-Shirt V4",
    brand: "GRAPHL",
    price: 999,
    comparePrice: 1499,
    description: "Clean minimal oversized fit built for the streets.",
    images: ["/products/tshirts/tshirt8.jpg", "/products/tshirts/tshirt10.png"],
    colors: [{ name: "Grey", hex: "#888888" }, { name: "Black", hex: "#111111" }],
    sizes: ["S", "M", "L", "XL"],
    category: "tshirts",
    stock: 75,
    featured: false,
    rating: 4.5,
    reviews: 95,
  },
  {
    id: 10,
    slug: "graphl-oversized-tshirt-v5",
    title: "Graphl Oversized T-Shirt V5",
    brand: "GRAPHL",
    price: 999,
    comparePrice: 1499,
    description: "Heavyweight cotton tee with a relaxed oversized silhouette.",
    images: ["/products/tshirts/tshirt11.png", "/products/tshirts/tshirt12.png"],
    colors: [{ name: "White", hex: "#F5F5F5" }, { name: "Olive", hex: "#556B2F" }],
    sizes: ["S", "M", "L", "XL"],
    category: "tshirts",
    stock: 60,
    featured: true,
    rating: 4.7,
    reviews: 130,
  },
  {
    id: 11,
    slug: "graphl-oversized-tshirt-v6",
    title: "Graphl Oversized T-Shirt V6",
    brand: "GRAPHL",
    price: 999,
    comparePrice: 1499,
    description: "Bold graphic tee made for those who stand out.",
    images: ["/products/tshirts/tshirt14.png", "/products/tshirts/tshirt22.png"],
    colors: [{ name: "Black", hex: "#111111" }],
    sizes: ["S", "M", "L", "XL"],
    category: "tshirts",
    stock: 50,
    featured: false,
    rating: 4.8,
    reviews: 88,
  },
  {
    id: 12,
    slug: "graphl-oversized-tshirt-v7",
    title: "Graphl Oversized T-Shirt V7",
    brand: "GRAPHL",
    price: 999,
    comparePrice: 1499,
    description: "Signature Graphl oversized drop in a fresh new colourway.",
    images: ["/products/tshirts/tshirt24.png"],
    colors: [{ name: "Charcoal", hex: "#333333" }, { name: "White", hex: "#F5F5F5" }],
    sizes: ["S", "M", "L", "XL"],
    category: "tshirts",
    stock: 70,
    featured: false,
    rating: 4.6,
    reviews: 74,
  },
  {
    id: 13,
    slug: "graphl-oversized-tshirt-v8",
    title: "Graphl Oversized T-Shirt V8",
    brand: "GRAPHL",
    price: 999,
    comparePrice: 1499,
    description: "Street-ready oversized tee with premium stitching.",
    images: ["/products/tshirts/tshirt26.png", "/products/tshirts/tshirt27.png"],
    colors: [{ name: "Black", hex: "#111111" }, { name: "Grey", hex: "#888888" }],
    sizes: ["S", "M", "L", "XL"],
    category: "tshirts",
    stock: 65,
    featured: false,
    rating: 4.5,
    reviews: 62,
  },
  {
    id: 14,
    slug: "graphl-oversized-tshirt-v9",
    title: "Graphl Oversized T-Shirt V9",
    brand: "GRAPHL",
    price: 999,
    comparePrice: 1499,
    description: "Effortless style meets heavyweight comfort in every drop.",
    images: ["/products/tshirts/tshirt28.png", "/products/tshirts/tshirt29.png"],
    colors: [{ name: "White", hex: "#F5F5F5" }, { name: "Black", hex: "#111111" }],
    sizes: ["S", "M", "L", "XL"],
    category: "tshirts",
    stock: 55,
    featured: true,
    rating: 4.9,
    reviews: 145,
  },
  {
    id: 15,
    slug: "graphl-oversized-tshirt-v10",
    title: "Graphl Oversized T-Shirt V10",
    brand: "GRAPHL",
    price: 999,
    comparePrice: 1499,
    description: "The latest Graphl tee — minimal design, maximum impact.",
    images: ["/products/tshirts/tshirt30.png"],
    colors: [{ name: "Olive", hex: "#556B2F" }, { name: "Black", hex: "#111111" }],
    sizes: ["S", "M", "L", "XL"],
    category: "tshirts",
    stock: 45,
    featured: false,
    rating: 4.7,
    reviews: 58,
  },
  {
    id: 16,
    slug: "graphl-oversized-tshirt-v11",
    title: "Graphl Oversized T-Shirt V11",
    brand: "GRAPHL",
    price: 999,
    comparePrice: 1499,
    description: "Raw streetwear energy packed into every stitch.",
    images: ["/products/tshirts/tshirt32.png"],
    colors: [{ name: "Black", hex: "#111111" }],
    sizes: ["S", "M", "L", "XL"],
    category: "tshirts",
    stock: 40,
    featured: false,
    rating: 4.6,
    reviews: 49,
  },
  {
    id: 17,
    slug: "graphl-oversized-tshirt-v12",
    title: "Graphl Oversized T-Shirt V12",
    brand: "GRAPHL",
    price: 999,
    comparePrice: 1499,
    description: "Limited colourway. Unlimited attitude.",
    images: ["/products/tshirts/tshirt33.png"],
    colors: [{ name: "White", hex: "#F5F5F5" }, { name: "Grey", hex: "#888888" }],
    sizes: ["S", "M", "L", "XL"],
    category: "tshirts",
    stock: 35,
    featured: false,
    rating: 4.8,
    reviews: 41,
  },

  // ─── STREETWEAR ────────────────────────────────────────

 // ─── STREETWEAR ────────────────────────────────────────
  {
    id: 18,
    slug: "graphl-streetwear-v1",
    title: "Graphl Streetwear V1",
    brand: "GRAPHL",
    price: 2499,
    comparePrice: 3199,
    description: "Statement pieces built for the streets. Wear it bold.",
    images: ["/products/hoodies/streetwear1.jpg"],
    colors: [{ name: "Black", hex: "#111111" }],
    sizes: ["S", "M", "L", "XL"],
    category: "streetwear",
    stock: 30,
    featured: true,
    rating: 4.9,
    reviews: 76,
  },
  {
    id: 19,
    slug: "graphl-streetwear-v2",
    title: "Graphl Streetwear V2",
    brand: "GRAPHL",
    price: 2499,
    comparePrice: 3199,
    description: "Raw energy, refined silhouette. Built for the bold.",
    images: ["/products/hoodies/streetwear2.jpg"],
    colors: [{ name: "Grey", hex: "#888888" }, { name: "Black", hex: "#111111" }],
    sizes: ["S", "M", "L", "XL"],
    category: "streetwear",
    stock: 25,
    featured: false,
    rating: 4.7,
    reviews: 54,
  },
  {
    id: 20,
    slug: "graphl-streetwear-v3",
    title: "Graphl Streetwear V3",
    brand: "GRAPHL",
    price: 2499,
    comparePrice: 3199,
    description: "Everyday streetwear with an edge. No compromises.",
    images: ["/products/hoodies/streetwear3.jpg"],
    colors: [{ name: "Olive", hex: "#556B2F" }, { name: "Black", hex: "#111111" }],
    sizes: ["S", "M", "L", "XL"],
    category: "streetwear",
    stock: 20,
    featured: false,
    rating: 4.6,
    reviews: 41,
  },
  {
    id: 21,
    slug: "graphl-streetwear-v4",
    title: "Graphl Streetwear V4",
    brand: "GRAPHL",
    price: 2499,
    comparePrice: 3199,
    description: "Clean cuts, street-ready attitude. A Graphl essential.",
    images: ["/products/hoodies/streetwear4.jpg"],
    colors: [{ name: "White", hex: "#F5F5F5" }, { name: "Charcoal", hex: "#333333" }],
    sizes: ["S", "M", "L", "XL"],
    category: "streetwear",
    stock: 28,
    featured: true,
    rating: 4.8,
    reviews: 63,
  },
  {
    id: 22,
    slug: "graphl-streetwear-v5",
    title: "Graphl Streetwear V5",
    brand: "GRAPHL",
    price: 2499,
    comparePrice: 3199,
    description: "Oversized comfort meets street culture in every stitch.",
    images: ["/products/hoodies/streetwear5.jpg"],
    colors: [{ name: "Black", hex: "#111111" }],
    sizes: ["S", "M", "L", "XL"],
    category: "streetwear",
    stock: 18,
    featured: false,
    rating: 4.5,
    reviews: 37,
  },
  {
    id: 23,
    slug: "graphl-streetwear-v6",
    title: "Graphl Streetwear V6",
    brand: "GRAPHL",
    price: 2499,
    comparePrice: 3199,
    description: "Limited drop. Unlimited swagger. Only for the few.",
    images: ["/products/hoodies/streetwear6.jpg"],
    colors: [{ name: "Brown", hex: "#5C3A1E" }, { name: "Black", hex: "#111111" }],
    sizes: ["S", "M", "L", "XL"],
    category: "streetwear",
    stock: 15,
    featured: true,
    rating: 4.9,
    reviews: 29,
  },
  {
    id: 24,
    slug: "graphl-streetwear-v7",
    title: "Graphl Streetwear V7",
    brand: "GRAPHL",
    price: 2499,
    comparePrice: 3199,
    description: "The final drop in the streetwear series. Don't sleep on it.",
    images: ["/products/hoodies/streetwear7.jpg"],
    colors: [{ name: "Charcoal", hex: "#333333" }, { name: "White", hex: "#F5F5F5" }],
    sizes: ["S", "M", "L", "XL"],
    category: "streetwear",
    stock: 12,
    featured: false,
    rating: 4.7,
    reviews: 22,
  },

  // ─── SPL EDITION ───────────────────────────────────────
  {
    id: 19,
    slug: "graphl-spl-edition-drop-01",
    title: "Graphl #SPL Edition — Drop 01",
    brand: "GRAPHL",
    price: 2999,
    comparePrice: 3999,
    description: "Exclusive limited drop. Once it's gone, it's gone. Only for the bold.",
    images: ["/products/tshirts/tshirt22.png", "/products/hoodies/hoodie2.jpg"],
    colors: [{ name: "Black", hex: "#111111" }, { name: "Olive", hex: "#556B2F" }],
    sizes: ["S", "M", "L", "XL"],
    category: "spl-edition",
    stock: 15,
    featured: true,
    rating: 5.0,
    reviews: 42,
  },

];

export default graphlProducts;